#!/usr/bin/env python
import openai
import os
import subprocess
import readline

openai.api_key = os.environ.get("CHAT_GPT_API_KEY")

readline.parse_and_bind("set editing-mode vi")
readline.parse_and_bind("Control-h: backward-delete-char")


messages = []
system_msg = '''
あなたはプログラマーのためのアシスタント。
'''

BG_CYAN_FG_WHITE = "\033[46m\033[37m"
RESET_ES = "\033[0m"

messages.append({"role": "system", "content": system_msg})

print("Input your question please.")

print("")
while input != "q":
    message = input(BG_CYAN_FG_WHITE + "Input>" + RESET_ES + " ")
    if message == "":
        continue
    if message == "clear":
        clear_screen()
        continue
    messages.append({"role": "user", "content": message})
    response = openai.ChatCompletion.create(
            model="gpt-3.5-turbo",
            messages=messages,
            temperature=0.8,
            )
    reply = response["choices"][0]["message"]["content"]
    messages.append({"role": "assistant", "content": reply})

    output = subprocess.run(["echo", reply], stdout=subprocess.PIPE)
    output = subprocess.run(["glow"], input=output.stdout)


